# Generated by Django 4.2.20 on 2025-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "number_of_people",
                    models.FloatField(verbose_name="Number of people (thousands)"),
                ),
            ],
        ),
    ]
